---
- name: Install the Ambari Agent
  package:
    name: ambari-agent
    update_cache: yes
    state: latest
  notify: Reload systemd

- name: Set the Ambari Server in the agent configuration
  lineinfile:
    dest: /etc/ambari-agent/conf/ambari-agent.ini
    regexp: "^hostname="
    line: "hostname={{ hostvars[groups['ambari-server']|sort|list|first]['ansible_fqdn'] }}"
    state: present

- name: Strains ambari agent to use force_https_protocol=PROTOCOL_TLSv1_2
  ini_file:
    dest: /etc/ambari-agent/conf/ambari-agent.ini
    section: security
    option: force_https_protocol
    value: PROTOCOL_TLSv1_2
    state: present
  notify: Restart ambari-agent

- meta: flush_handlers

- name: Make sure the ambari-agent service is started
  service:
    name: ambari-agent
    state: started

- name: Make sure the ambari-agent service is enabled
  service:
    name: ambari-agent
    enabled: yes
  ignore_errors: true
